"""fix: ids

Revision ID: ba1cc9eca431
Revises: bf21c0e49cbd
Create Date: 2026-06-18 19:37:15.997983
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ba1cc9eca431"
down_revision = "bf21c0e49cbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_MCT_auth_email"), table_name="MCT_auth")
    op.create_index(op.f("ix_MCT_auth_email"), "MCT_auth", ["email"], unique=False)
    op.create_index(
        op.f("ix_MCT_jids_jupyter_id"), "MCT_jids", ["jupyter_id"], unique=True
    )
    op.create_index(op.f("ix_MCT_jids_kc_id"), "MCT_jids", ["kc_id"], unique=True)
    op.create_index(
        op.f("ix_MCT_jids_moodle_id"), "MCT_jids", ["moodle_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_MCT_jids_moodle_id"), table_name="MCT_jids")
    op.drop_index(op.f("ix_MCT_jids_kc_id"), table_name="MCT_jids")
    op.drop_index(op.f("ix_MCT_jids_jupyter_id"), table_name="MCT_jids")
    op.drop_index(op.f("ix_MCT_auth_email"), table_name="MCT_auth")
    op.create_index(op.f("ix_MCT_auth_email"), "MCT_auth", ["email"], unique=True)
    # ### end Alembic commands ###
